version: "3.8"

services:
  ld-dev-server:
    image: launchdarkly/ldcli:1.9.0
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O /dev/null http://localhost:8765/ui/" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8765:8765"
    entrypoint: sh
    command:
      - -ec
      - |
        /ldcli dev-server start --source $LD_SOURCE_ENV --project $LD_SOURCE_PROJECT --context '$LD_CONTEXT' --override '$LD_LOCAL_OVERRIDES'
    environment:
      - LD_ACCESS_TOKEN=$LD_ACCESS_TOKEN
  app:
    build:
      context: ./app
    environment:
      - LD_SDK_KEY=$LD_SOURCE_PROJECT
      - APP_FLAG_KEY=$APP_FLAG_KEY
      - LD_BASE_URI=http://ld-dev-server:8765
    depends_on:
      ld-dev-server:
        condition: service_healthy